de-caffeine/de-caffeine

- src/App.tsx
- src/components/atoms/Logo.tsx
- src/css/font.css
- src/css/index.css
> #4 
> logo 생성 후 dev 브랜치로 다시 pr
>
> Feature: atoms/  logo #4

- src/components/atoms/Button.tsx
- hover시 cursor-pointer 적용
- **size** : s, m l로 크기 조정
- **full?** : 배경색 적용
- **onClick** : 클릭 이벤트 함수
- **children** : 버튼 내용
```jsx
import Button from "./components/atoms/Button";
export default function App() {
const onClick = () => {};
return (
<div className="flex flex-col gap-2 m-3">
<Button size="s" onClick={onClick}>
언팔로우
</Button>
<Button size="m" onClick={onClick}>
Log In
</Button>
<Button size="l" onClick={onClick}>
로그인
</Button>
<Button full size="s" onClick={onClick}>
팔로우
</Button>
<Button full size="m" onClick={onClick}>
Sign Up
</Button>
<Button full size="l" onClick={onClick}>
회원 가입
</Button>
</div>
);
}
```
> Feat: atoms / Button 컴포넌트 퍼블리싱

- src/components/atoms/AlarmListItem.tsx
> AlarmListItem 컴포넌트 퍼블리싱 #16
> 알림 리스트 아이템 제작
- 콘텐츠 크기에 맞게 줄바꿈처리
- 내용이 2줄 이상 넘어갈 시 말줄임(...) 표시
> Feat: atoms / AlarmListItem 컴포넌트 퍼블리싱

- src/components/molecules/Card.tsx
- src/components/molecules/CommentCard.tsx
>#32
댓글 카드
- title 1줄, comment 2줄 넘어갈 시 말줄임(...) 처리
- 부모 요소의 width 100%
- **title**: string
- **comment**: string
figma에서 title의 제목이 14px로 되어있어서 18px로 작성했는데 괜찮은 것 같나요?
```jsx
import CommentCard from "./components/molecules/CommentCard";
export default function App() {
return <div className="flex flex-col w-[60%] items-center mt-10 mx-auto gap-[15px]">
<CommentCard title="이거 왜이러나요" comment="두 조건 중 하나라도 만족하면 미인증 사용자로 간주하여 리다이렉트합니다. 따라서, OR 조건이 적합하며, 세션이 없는 경우는 물론이고, 세션이 존재하더라도 로그인 정보가 존재하지 않는 경우 모두를 포괄할 수 있습니다. 도용된 세션에 대한 우려는 인증 및 세션 관리 이외의 보안 메커니즘 (예: 세션 만료 시간 설정, 세션 고정 공격 방지 등)을 활용하여 해결해야 합니다. 이는 해당 조건문에서 직접적으로 해결할 수 있는 문제가 아닙니다."/>
<CommentCard title="이거 왜이러나요" comment="두 조건 중 하나라도 만족하면 미인증 사용자로 간주하여 리다이렉트합니다. 따라서, OR 조건이 적합하며, 세션이 없는 경우는 물론이고, 세션이 존재하더라도 로그인 정보가 존재하지 않는 경우 모두를 포괄할 수 …
```
> Feat: molecules / CommentCard 컴포넌트 퍼블리싱

- package.json
- src/App.tsx
- src/api/auth.ts
- src/api/channels.ts
- src/api/comments.ts
- src/api/follow.ts
- src/api/index.ts
- src/api/likes.ts
- src/api/messages.ts
- src/api/notifications.ts
- src/api/posts.ts
- src/api/search.ts
- src/api/users.ts
> #34
> api를 정리해서 작업했습니다 모든 api가 제대로 작동하는지 체크를 하진 못해서 추후에 다른 오류가 발생할수도있지만 이미지 업로드 부분에서 도중에 문제가 발생해서 수정해서 이미지 올라가게 확인하였습니다 
>
>
> ✨:Feat API 추가

- src/components/atoms/BreadCrumb.tsx
> #37 
> breadcrumb 생성
[push 한 코드] BreadCrumb.tsx 만 push 했습니다 !
```
export default function BreadCrumb() {
return (
<>
<div>
<span className="nanum-gothic-regular">
{/* <Link to="/">홈 {">"}</Link> */}
홈 {">"}
</span>
<span className="nanum-gothic-regular">
{/* <Link to="/community">커뮤니티 {">"}</Link> */}
커뮤니티 {">"}
</span>
{/* 
communityTitle은 해당 페이지 props 로 받기
pathname는 Route에서  받기 
Route path='/community/velog' element={<CommunityVelogPage/>}
*/}
<span className="nanum-gothic-regular">
{/* <Link to={pathname}>{communityTitle}</Link> */}
일상공유
</span>
</div>
</>
);
}
```
>
route Link 사용해서 작성했을 때는 연결된 페이지가 없어서 렌더링이 되지 않는 것 같아요 확인해주세요.
밑에 이미지는 렌더링만 확인하려고 link를 뺀 상태입니다. 
어디까지 컴포넌트를 짜야할지 몰라 일단 link 사용해서 페이지 이동가능하도록 해봤습니다.
>  Feat: BreadCrumb 생성 #37

- src/components/molecules/QuestionCard.tsx
> ex) #39 
> tag는 pr 올라와 있는 기준으로 작성했고, info에 name으로 props줘서 적용해두었습니다
```
import QuestionCard from './components/molecules/QuestionCard';
export default function App() {
return (
<>
<div className="m-3 flex flex-col gap-2">
<QuestionCard
title="나는 고양이이이이이이이"
content=" 내용 "
solved={true}
tags={['CMD', 'BlueScreen']}
name="NaverFE"
timestamp={new Date()}
commentCount={0}
likeCount={0}
isLike={true}
/>
</div>
</>
);
}
```
>
> ✨ Feat: QuestionCard 컴포넌트 추가

- src/components/molecules/UserCard.tsx
> #46 
UserCard 생성 
Tag 렌더링 -  반복렌더링으로 작성
test로 만든 스샷입니다. 참고만해주세요. 
이름과 태그는 props 로 받아서 렌더링합니다. 
props 필요한 부분 다 쓴 것 같은데 추가할 부분이 있다던가 수정해야할 부분이 있다면 얘기해주세요!
> Feat: molecules - UserCard 제작 #46

- src/global.d.ts
> #55
> api에 관한 전역 타입을 작성했습니다.
추후에도 전역 타입에 넣을만 한 게 있다면 말씀해주세요!
> Feat: 전역 타입 작성

- src/api/posts.ts
- src/components/atoms/ChattingListItem.tsx
- src/components/atoms/Info.tsx
- src/components/atoms/TimeAgo.tsx
- src/components/atoms/UserAvatar.tsx
> #47
> 채팅방에 보여지는 상대방 목록추가했습니다 카카오톡과같이 300개이상의메시지는 +로 처리했습니다
> 그밖에도 post API에 제목말고 본문받는내용이없어서 같이 수정하고 주석 몇개 달았습니다
>
> 47 chatting list item

- src/components/atoms/FloatingButton.tsx
> #15 
> Props 받아서 3가지 용도로 사용할 수 있도록 처리
> 사용예시
> 이렇게 하면 잘 사용할 수 있는지 확인 부탁드립니다.
> Feat : atoms / FloatingButton - props 수정 #15

- src/global.d.ts
> #55
> 이미지에는 null값을 할당 할 수 없습니다.
> Fix : 전역 타입 image에 null 삭제

- src/api/posts.ts
> ex) post API에 tags 추가했습니다
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
>
> ♻️ :Refactor post API에 tags 추가

- src/components/molecules/LoginPopup.tsx
- src/loginStore.ts
> #84
> 사용자가 로그인 했을 때 내 유저 정보를 전역변수에 저장합니다.
```ts
myInfo: {} // 유저 정보를 담는 변수 (초깃값: {})
saveLoginInfo: (info) => set({ myInfo: info }) // 유저정보를 저장하는 메소드 (로그인에 사용)
updateLoginInfo: (info) => set({ myInfo: info }), // 유저정보를 업데이트하는 메소드 (포스트/댓글 작성, 좋아요, 알람, 채팅 등 사용자가 어떤 행동을 할 때 사용)
deleteLoginInfo: () => set({ myInfo: {} }), // 유저정보를 {}로 초기화하는 메소드 (로그아웃, 회원탈퇴에 사용)
```
```ts
import { useLoginStore } from '../../loginStore'; // loginStore를 import해옵니다.
const { saveLoginInfo } = useLoginStore(); // 사용할 함수를 꺼내옵니다.
saveLoginInfo(res); // 함수 사용
/* 전역변수 안에 있는 값을 사용하고 싶을 때 */
useLoginStore.getState().myInfo
```
> Feat : 로그인 정보 전역 관리

- src/components/templates/NotFound.tsx
> #81
> NotFound 템플릿 퍼블리싱
디자인 수정할 부분 있으면 말씀해주세요
> Feat : NotFound 페이지 제작

- src/components/molecules/User.tsx
- src/components/organisms/Header.tsx
- src/components/templates/UserPage.tsx
> #68 
>내가 단 댓글 보기 기능 추가, 팔로우 버튼 수정, HEADER 부분 Link to 부분 수정
>
> REFACTOR : template / UserPage #68

- src/components/organisms/Header.tsx
> 
> Header 부분 merge 시 누락된 부분 추가 및 수정 
>
> Fix : Header.tsx 머지 시 누락 부분 수정 

- src/components/atoms/SubNavigation.tsx
- src/components/molecules/User.tsx
- src/components/templates/UserPage.tsx
- src/components/templates/Users.tsx
> #68 
> 
유효하지 않은 id 값 notfound 404 처리
follow 상태 추가 -> 팔로우 버튼 기능 정상작동
user 계정 클릭 후 새창으로 페이지 렌더링 (https 처리)
>
> FIX : UserPage.tsx - 유효하지 않은 id 값 not found  및 기타 수정

- src/components/molecules/AlarmIcon.tsx
- src/components/templates/Community.tsx
- src/components/templates/Question.tsx
- src/components/templates/Search.tsx
> #83
> Alarm 무한 리렌더링 오류 해결, 예외처리 추가, LoginStore 적용
> Fix : Alarm 무한 리렌더링 오류 해결, 예외처리 추가 등

- src/App.tsx
- src/components/templates/UserPage.tsx
> #68 
404 페이지 뜨지 않는 부분 수정
404 페이지 렌더링 후 뒤로가기 버튼 되지 않는 부분 확인 후 수정 (리다이렉트 하지 않고 404 페이지 렌더링으로 해결)
(선택)
현우님 작성해주신 부분 중에 avatarUrl 부분 빨간줄 가는데 확인부탁드려요
> Fix : UserPage.tsx 404 페이지 렌더링 오류 수정

- src/components/templates/UserPage.tsx
> #68 
> 로그아웃 후에도 나오는  filledHeart 렌더링 오류 수정
>
> Fix : UserPage.tsx #68 - filledHeart 렌더링 오류 수정

- src/components/atoms/Tag.tsx
- src/components/molecules/AlarmIcon.tsx
- src/components/molecules/QuestionCardSkeleton.tsx
- src/components/molecules/UserCardSkeleton.tsx
- src/components/organisms/Header.tsx
- src/components/templates/Search.tsx
> Design: Search 페이지 스켈레톤 적용

- src/components/templates/UserPage.tsx
>  #73
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
>
> ♻️ :Refactor 로그인 안하면 유저페이지에서 채팅버튼 안보이는이슈 수정

- src/components/atoms/Button.tsx
- src/components/molecules/UserCard.tsx
- src/components/organisms/Header.tsx
- src/components/templates/Search.tsx
- src/components/templates/UserPage.tsx
> Refactor: CSS, BugFix
